# Generated by Django 6.1.1 on 2026-09-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  # noqa: RUF012
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Python', 'Python'), ('AI', 'AI'), ('Security', 'Security'), ('Web', 'Web'), ('Cloud', 'Cloud'), ('Ideas', 'Ideas')], default='Ideas', max_length=30)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
