# Generated by Django 6.1.1 on 2026-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('notes', '0001_initial'),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['category'], name='note_category_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='note_created_idx'),
        ),
    ]
